import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import datetime
import streamlit as st

# --- SECURE EMAIL CONFIG ---
try:
    EMAIL_SENDER = st.secrets["EMAIL_SENDER"]
    EMAIL_PASSWORD = st.secrets["EMAIL_PASSWORD"]
except:
    EMAIL_SENDER = "audit.ledgerflux@gmail.com"
    EMAIL_PASSWORD = "otyf wtfh jwhw kywf"

def generate_html_report(invoice_id, carrier, status, total_billed, total_savings, details_df):
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica', sans-serif; color: #333; padding: 40px; background-color: #f4f4f4; }}
            .container {{ background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 15px rgba(0,0,0,0.1); max-width: 850px; margin: auto; }}
            .header {{ display: flex; justify-content: space-between; border-bottom: 3px solid #6C5DD3; padding-bottom: 20px; margin-bottom: 30px; }}
            .logo {{ font-size: 28px; font-weight: 800; color: #6C5DD3; letter-spacing: -1px; }}
            .status-box {{ padding: 8px 16px; border-radius: 4px; font-weight: bold; font-size: 14px; color: white; background-color: {'#FF5252' if status == 'Discrepancy' else '#00E676'}; }}
            .metrics {{ display: flex; gap: 20px; margin-bottom: 40px; }}
            .metric {{ background: #f8f9fa; padding: 20px; border-radius: 8px; width: 100%; border: 1px solid #eee; }}
            .metric h3 {{ margin: 0 0 5px 0; font-size: 12px; text-transform: uppercase; color: #888; letter-spacing: 1px; }}
            .metric p {{ margin: 0; font-size: 24px; font-weight: 700; color: #333; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th {{ text-align: left; background: #f1f1f1; padding: 12px; font-size: 12px; font-weight: 700; color: #555; text-transform: uppercase; }}
            td {{ padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; color: #444; }}
            tr:last-child td {{ border-bottom: none; }}
            .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #aaa; text-align: center; }}
            .print-btn {{ background-color: #333; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; margin-bottom: 20px; cursor: pointer; }}
            @media print {{ .print-btn {{ display: none; }} body {{ background-color: white; padding: 0; }} .container {{ box-shadow: none; border: none; }} }}
        </style>
    </head>
    <body>
        <div class="container">
            <div style="text-align: right;">
                <a onclick="window.print()" class="print-btn">🖨️ Save as PDF</a>
            </div>
            <div class="header">
                <div class="logo">⚡ LedgerFlux</div>
                <div class="status-box">{status.upper()}</div>
            </div>
            
            <div class="metrics">
                <div class="metric">
                    <h3>Audit Reference</h3>
                    <p>{invoice_id}</p>
                </div>
                <div class="metric">
                    <h3>Invoiced Amount</h3>
                    <p>₹ {total_billed:,.2f}</p>
                </div>
                <div class="metric">
                    <h3>Recoverable Funds</h3>
                    <p style="color: {'#FF5252' if total_savings > 0 else '#333'}">₹ {total_savings:,.2f}</p>
                </div>
            </div>

            <h3 style="margin-bottom: 15px; font-size: 16px;">Line Item Breakdown ({carrier})</h3>
            {details_df.to_html(index=False, border=0)}

            <div class="footer">
                Generated by LedgerFlux Universal Audit Engine • {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}
                <br>This document is a certified financial audit record.
                def send_real_email(to_email, subject, body, html_content=None, filename="Audit_Report.html")
            </div>
        </div>
    </body>

    </html>
    """