import requests
import json
import datetime

def generate_html_report(audit_id, carrier, status, total_billed, total_savings, df_details):
    """Generates the Master HTML Certificate for the audit."""
    
    # Safely handle the dataframe to HTML conversion
    try:
        table_html = df_details.to_html(index=False, classes="audit-table")
    except Exception:
        table_html = "<p><i>Line item details unavailable.</i></p>"

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>LedgerFlux Audit: {audit_id}</title>
        <style>
            body {{ font-family: 'Inter', Arial, sans-serif; background-color: #f4f7f6; color: #333; padding: 40px; }}
            .container {{ max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }}
            .header {{ border-bottom: 2px solid #6C5DD3; padding-bottom: 10px; margin-bottom: 20px; }}
            h1 {{ color: #111; margin: 0; }}
            .status {{ display: inline-block; padding: 5px 12px; border-radius: 4px; font-weight: bold; background-color: {'#ffebee' if total_savings > 0 else '#e8f5e9'}; color: {'#c62828' if total_savings > 0 else '#2e7d32'}; }}
            .metrics {{ display: flex; justify-content: space-between; background: #fafafa; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
            .metric-box {{ text-align: center; }}
            .audit-table {{ width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }}
            .audit-table th {{ background-color: #f0f0f0; padding: 12px; text-align: left; border-bottom: 2px solid #ddd; }}
            .audit-table td {{ padding: 12px; border-bottom: 1px solid #eee; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #777; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>⚡ LedgerFlux Official Audit</h1>
                <p><strong>Reference ID:</strong> {audit_id} | <strong>Carrier:</strong> {carrier} | <strong>Date:</strong> {datetime.datetime.now().strftime("%Y-%m-%d")}</p>
                <div class="status">{status.upper()}</div>
            </div>
            
            <div class="metrics">
                <div class="metric-box">
                    <strong>Total Billed</strong><br>
                    <span style="font-size: 20px;">₹ {total_billed:,.2f}</span>
                </div>
                <div class="metric-box">
                    <strong>Recoverable Leakage</strong><br>
                    <span style="font-size: 20px; color: #c62828;">₹ {total_savings:,.2f}</span>
                </div>
            </div>

            <h3>Line Item Analysis</h3>
            {table_html}

            <div class="footer">
                <p>This is a certified digital audit generated by the LedgerFlux Enterprise Engine.</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def send_real_email(to_email, subject, body, html_content=None, filename="Audit_Report.html"):
    """
    Enterprise Routing: Bypasses Python SMTP and hands the payload to the Node.js Mailer API.
    """
    url = "https://ledgerflux-engine.onrender.com/api/mail/send"
    
    payload = {
        "to": to_email,
        "subject": subject,
        "text": body,
        "html_content": html_content,
        "filename": filename
    }
    
    headers = {"Content-Type": "application/json"}
    
    try:
        response = requests.post(url, data=json.dumps(payload), headers=headers, timeout=10)
        if response.status_code == 200:
            return True, "Email handed off to Node.js relay."
        else:
            return False, f"API Error: {response.text}"
    except requests.exceptions.ConnectionError:
        return False, "Connection to Node.js failed. Is Port 3000 running?"
    except Exception as e:
        return False, f"Transmission error: {str(e)}"