const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'YOUR_GMAIL_ADDRESS@gmail.com', // Enter your email
        pass: 'YOUR_16_CHAR_APP_PASSWORD'     // Enter the App Password here (no spaces)
    }
});

// Make sure your dispatch route is ready
app.post('/api/dispatch-certificate', async (req, res) => {
    const { to_email, audit_data } = req.body;

    const htmlCertificate = `
        <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; max-width: 600px;">
            <h2 style="color: #d9534f; margin-top: 0;">LedgerFlux Forensic Alert</h2>
            <p><strong>Invoice Reference:</strong> ${audit_data.invoice_ref}</p>
            <p><strong>Carrier:</strong> ${audit_data.carrier}</p>
            <hr style="border: 1px solid #eee; margin: 20px 0;"/>
            <h3 style="color: #292b2c;">Leakage Detected: <span style="color: #d9534f;">${audit_data.leakage_amount}</span></h3>
            <p><strong>Audit Finding:</strong> ${audit_data.reason}</p>
            <br/>
            <p style="font-size: 12px; color: #777;"><em>This certificate is auto-generated by the LedgerFlux Engine. Forward directly to your carrier representative to request a credit.</em></p>
        </div>
    `;

    const mailOptions = {
        from: 'YOUR_GMAIL_ADDRESS@gmail.com', // Must match auth user
        to: to_email,
        subject: `ACTION REQUIRED: Invoice Discrepancy Found (${audit_data.leakage_amount})`,
        html: htmlCertificate
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log(`[+] Certificate dispatched to ${to_email}`);
        res.status(200).json({ message: "Dispatched" });
    } catch (error) {
        console.error("[-] Node Mailer Error:", error);
        res.status(500).json({ error: "Failed to dispatch" });
    }
});
const express = require('express');
const cors = require('cors');
const multer = require('multer');
const AdmZip = require('adm-zip');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const { PrismaClient } = require('@prisma/client');

console.log("\n[BOOT] Powering up LedgerFlux Enterprise Engine...");
const prisma = new PrismaClient();
const app = express();

// --- 1. ENTERPRISE MIDDLEWARE ---
app.use(cors());
app.use(express.json({ limit: '100mb' }));
app.use(express.urlencoded({ limit: '100mb', extended: true }));

const uploadDir = path.join(__dirname, '../uploads');
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });
const upload = multer({ dest: uploadDir });

// --- 2. DATABASE SEEDER ---
async function initializeDB() {
    try {
        await prisma.client.upsert({
            where: { id: "OMNIACTIVE-UUID-001" },
            update: {},
            create: { id: "OMNIACTIVE-UUID-001", company_name: "OmniActive Health" }
        });
        console.log("[BOOT] System Client 'OMNIACTIVE-UUID-001' verified in Supabase.");
    } catch (e) {
        console.error("[BOOT ERROR] Database connection failed.", e.message);
    }
}
initializeDB();

// --- 3. THE DOORS (ROUTES) ---
app.get('/', (req, res) => res.send("⚡ LedgerFlux API is Online and Routing Traffic."));

app.get('/health', async (req, res) => {
    try {
        await prisma.$queryRaw`SELECT 1`;
        res.status(200).json({ status: "Database Connected ⚡" });
    } catch (e) {
        res.status(500).json({ status: "Database Offline", error: e.message });
    }
});

app.get('/api/audits/summary', async (req, res) => {
    try {
        const audits = await prisma.audit.findMany({ orderBy: { timestamp: 'desc' }, take: 50 });
        res.json(audits);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// --- 4. BATCH PROCESSOR (UI DRIVEN) ---
app.post('/api/upload/batch', upload.single('file'), async (req, res) => {
    let extractDir = null;
    try {
        if (!req.file) return res.status(400).json({ error: "No ZIP file provided." });

        const zip = new AdmZip(req.file.path);
        extractDir = path.join(uploadDir, `batch_${Date.now()}`);
        zip.extractAllTo(extractDir, true);
        if (fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);

        const files = fs.readdirSync(extractDir).filter(f => f.toLowerCase().endsWith('.pdf'));
        console.log(`[SYS] UI Batch: Unpacked ${files.length} PDFs. Engaging Workers...`);

        const processedResults = [];
        let total_billed = 0;
        let total_savings = 0;

        for (const file of files) {
            const filePath = path.join(extractDir, file);
            await new Promise((resolve) => {
                exec(`python3 core/analyzer.py "${filePath}"`, async (err, stdout) => {
                    if (err) { console.error(`[PY ERROR] ${err.message}`); return resolve(); }
                    try {
                        const jsonMatch = stdout.match(/\{[\s\S]*\}/);
                        const result = JSON.parse(jsonMatch[0]);
                        
                        await prisma.audit.create({
                            data: {
                                clientId: "OMNIACTIVE-UUID-001", invoice_number: result.invoice_id,
                                carrier_name: result.carrier, status: result.status,
                                total_billed: result.total_billed, total_savings: result.total_savings
                            }
                        });
                        processedResults.push({"Invoice ID": result.invoice_id, "Carrier": result.carrier, "Status": result.status, "Billed": result.total_billed, "Recoverable": result.total_savings});
                        total_billed += result.total_billed; total_savings += result.total_savings;
                    } catch (e) { console.error("[PARSE ERROR]", e.message); }
                    resolve();
                });
            });
        }
        
        if (fs.existsSync(extractDir)) fs.rmSync(extractDir, { recursive: true, force: true });

        res.status(200).json({ message: "Batch processed.", results: processedResults, total_billed, total_savings });
    } catch (err) {
        if (extractDir && fs.existsSync(extractDir)) fs.rmSync(extractDir, { recursive: true, force: true });
        if (!res.headersSent) res.status(500).json({ error: "Server Error" });
    }
});

// --- 5. AUTOMATED DISPUTE RELAY ---
app.post('/api/mail/send', async (req, res) => {
    try {
        const { to, subject, text, html_content, filename } = req.body;
        const testAccount = await nodemailer.createTestAccount();
        const transporter = nodemailer.createTransport({ host: 'smtp.ethereal.email', port: 587, secure: false, auth: { user: testAccount.user, pass: testAccount.pass } });

        const mailOptions = {
            from: '"LedgerFlux" <disputes@ledgerflux.com>', to: to, subject: subject, text: text,
            html: `<div style="font-family: Arial;"><h2 style="color: #6C5DD3;">Automated Dispute</h2><p>${text}</p></div>`,
            attachments: [{ filename: filename || "Audit.html", content: html_content || "", contentType: 'text/html' }]
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`[MAIL SUCCESS] ID: ${info.messageId} | PREVIEW: ${nodemailer.getTestMessageUrl(info)}`);
        res.status(200).json({ message: "Dispute Sent" });
    } catch (err) { res.status(500).json({ error: "Mail failed" }); }
});

// --- 6. PHASE 4: THE ZERO-TOUCH WEBHOOK CONVEYOR BELT ---

// 6A. Security Middleware
const verifyWebhookKey = (req, res, next) => {
    const apiKey = req.headers['x-api-key'];
    if (apiKey !== "lf_live_enterprise_991") {
        console.log("[SECURITY] Blocked unauthorized webhook attempt.");
        return res.status(403).json({ error: "Unauthorized. Invalid LedgerFlux API Key." });
    }
    next();
};

// 6B. Auto-Ingest Route
app.post('/api/webhook/ingest', verifyWebhookKey, upload.single('file'), async (req, res) => {
    try {
        if (!req.file) return res.status(400).json({ error: "No PDF provided." });
        console.log(`\n[WEBHOOK] Secure Zero-Touch Payload Received. Auto-Auditing...`);

        const filePath = req.file.path;
        
        exec(`python3 core/analyzer.py "${filePath}"`, async (err, stdout) => {
            // Garbage Collection
            if (fs.existsSync(filePath)) fs.unlinkSync(filePath);

            if (err) return res.status(500).json({ error: "OCR Engine Failure" });
            
            try {
                const jsonMatch = stdout.match(/\{[\s\S]*\}/);
                const result = JSON.parse(jsonMatch[0]);
                
                // Save to Cloud DB
                await prisma.audit.create({
                    data: {
                        clientId: "OMNIACTIVE-UUID-001", invoice_number: result.invoice_id,
                        carrier_name: result.carrier, status: result.status,
                        total_billed: result.total_billed, total_savings: result.total_savings
                    }
                });
                
                console.log(`[WEBHOOK SUCCESS] Auto-audited Invoice ${result.invoice_id}. Savings: ₹${result.total_savings}`);
                res.status(200).json({ message: "Ingested & Audited", data: result });
            } catch (e) {
                console.error("[WEBHOOK ERROR]", e.message);
                res.status(500).json({ error: "Data processing failed" });
            }
        });
    } catch (err) {
        res.status(500).json({ error: "Webhook failure." });
    }
});

// --- 7. IGNITION ---
const PORT = 3000;
app.listen(PORT, '0.0.0.0', () => { 
    console.log(`====================================================`);
    console.log(`⚡ LEDGERFLUX API ROUTER ONLINE : PORT ${PORT}`);
    console.log(`====================================================\n`);
});
app.post('/api/dispatch-certificate', async (req, res) => {
    const { to_email, audit_data } = req.body;

    if (!to_email || !audit_data) {
        return res.status(400).json({ error: "Missing target email or audit data" });
    }

    // Your beautiful HTML format
    const htmlCertificate = `
        <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #d9534f;">LedgerFlux Discrepancy Alert</h2>
            <p><strong>Invoice Reference:</strong> ${audit_data.invoice_ref}</p>
            <p><strong>Carrier:</strong> ${audit_data.carrier}</p>
            <hr/>
            <h3 style="color: #292b2c;">Leakage Detected: <span style="color: #d9534f;">${audit_data.leakage_amount}</span></h3>
            <p><strong>Audit Finding:</strong> ${audit_data.reason}</p>
            <br/>
            <p><em>This certificate is auto-generated by the LedgerFlux Forensic Engine. Please forward this directly to your carrier representative to request a credit.</em></p>
        </div>
    `;

    const mailOptions = {
        from: 'audit@ledgerflux.com', // MUST match your authenticated domain
        to: to_email,
        subject: `ACTION REQUIRED: Invoice Discrepancy Found (${audit_data.leakage_amount})`,
        html: htmlCertificate
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log(`[+] Certificate dispatched to ${to_email}`);
        res.status(200).json({ message: "Certificate dispatched successfully" });
    } catch (error) {
        console.error("[-] Node Mailer Error:", error);
        res.status(500).json({ error: "Failed to dispatch certificate" });
    }
});