// server.js
const express = require('express');
const nodemailer = require('nodemailer');
const cors = require('cors');

const app = express();
app.use(express.json());
app.use(cors());

// =====================================================================
// PHASE 8: THE LIVE AMMO WEBHOOK RECEIVER
// =====================================================================
app.post('/api/audit/webhook', async (req, res) => {
    const { invoice_data } = req.body;
    
    console.log(`[*] INCOMING PAYLOAD: ${invoice_data.carrier} audit caught.`);
    console.log(`[*] Arming SMTP Relay...`);

    // 1. The Engine Setup
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: 'audit.ledgerflux@gmail.com',     // 🔴 CHANGE THIS: Your actual Gmail address
            pass: 'otyf wtfh jwhw kywf'   // 🔴 CHANGE THIS: The App Password (no spaces)
        }
    });

    // 2. The Enterprise HTML Template
    const mailOptions = {
        from: '"LedgerFlux Autonomous Audit" <YOUR_EMAIL@gmail.com>', // 🔴 CHANGE THIS: Your Gmail
        to: 'THE_CFO_EMAIL@gmail.com', // Change this to whoever you want the email to go to during the pitch
        subject: `URGENT: SLA Breach & Discrepancy Notice (${invoice_data.carrier})`,
        html: `
            <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; padding: 25px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
                <h2 style="color: #0f172a; margin-top: 0;">⚡ LedgerFlux Dispute Certificate</h2>
                <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                <p style="color: #475569; font-size: 16px;"><strong>Target Carrier:</strong> ${invoice_data.carrier}</p>
                <p style="color: #475569; font-size: 16px;"><strong>Violation Type:</strong> <span style="color: #ef4444; font-weight: 600;">${invoice_data.sla_status}</span></p>
                <p style="color: #475569; font-size: 16px;"><strong>Financial Impact:</strong> <span style="color: #10b981; font-size: 18px; font-weight: 800;">Actionable Leakage Isolated</span></p>
                <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                <p style="color: #64748b; font-size: 14px; line-height: 1.5;">This is an automated legal compliance notice generated by the LedgerFlux Forensic Engine. The carrier rate card has been triangulated against actual billed vectors.</p>
                <p style="color: #0f172a; font-size: 14px; font-weight: bold;">ACTION REQUIRED: Process credit memo within 48 hours to avoid AP holds.</p>
            </div>
        `
    };

    // 3. Fire the Payload
    try {
        await transporter.sendMail(mailOptions);
        console.log("[+] LIVE AMMO FIRED: Dispute Certificate successfully delivered.");
        res.status(200).send({ status: "Success", message: "Dispute Dispatched" });
    } catch (error) {
        console.error("[-] MISFIRE (Check Gmail Credentials):", error);
        res.status(500).send({ status: "Failed", error: error.message });
    }
});

app.listen(3000, () => {
    console.log('=============================================');
    console.log('⚡ LEDGERFLUX INVISIBLE PLUMBING ONLINE');
    console.log('⚡ Listening for Webhooks on Port 3000...');
    console.log('=============================================');
});